'use client';

import { useState } from "react";
import BookingSection from '@/components/BookingForm';
import BlurIn from '@/components/BlurIn';
import { CheckCircle2, Layout, ShoppingCart, Palette, Megaphone, Search, BarChart3, Smartphone, Code, Video, ShoppingBag, Wrench, Box, BookOpen } from "lucide-react";

/* =======================
   PRICING DATA (CATEGORIES)
======================= */

type PricingPlan = {
  name: string;
  price: string;
  description: string;
  features: string[];
  popular?: boolean;
};

type PricingCategoriesType = {
  [key: string]: PricingPlan[];
};

type CategoryIcon = {
  [key: string]: React.ReactNode;
};

const CATEGORY_ICONS: CategoryIcon = {
  "Web Design": <Layout size={20} />,
  "Shopify Package": <ShoppingBag size={20} />,
  "Web Maintenance Package": <Wrench size={20} />,
  "E-commerce Development": <ShoppingCart size={20} />,
  "Logo Design": <Palette size={20} />,
  "Branding": <Palette size={20} />,
  "Lead Generation": <Megaphone size={20} />,
  "SEO": <Search size={20} />,
  "Social Media Marketing": <BarChart3 size={20} />,
  "App Development": <Smartphone size={20} />,
  "Custom Development": <Code size={20} />,
  "Video Editing": <Video size={20} />,
  "3D Animation": <Box size={20} />,
  "Book Writing": <BookOpen size={20} />,
};




const PRICING_CATEGORIES: PricingCategoriesType = {
 "Web Design": [
  {
    name: "Basic",
    price: "$199",
    description: "Entry-level option for simple online presence with quick turnaround.",
    features: [
      "3 Page Website",
      "2 Stock Images",
      "1 jQuery Slider Banner",
      "Contact/Query Form",
      "24 to 48 hours TAT",
      "Complete Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Startup",
    price: "$399",
    description: "Great starter package for growing businesses needing more pages and basic SEO readiness.",
    popular: true, // Balanced price/features for startups
    features: [
      "5 Page Website",
      "5 Stock Photos",
      "3 Banner Designs",
      "1 jQuery Slider Banner",
      "FREE Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "24 to 48 hours TAT",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "Mobile Responsive – Additional $200",
      "CMS – Additional $250",
    ],
  },
  {
    name: "Professional",
    price: "$699",
    description: "Solid professional choice with CMS support, mobile responsiveness, and enhanced design elements.",
    features: [
      "10 Unique Pages Website",
      "CMS / Admin Panel Support",
      "8 Stock Images",
      "5 Banner Designs",
      "Mobile Responsive",
      "1 jQuery Slider Banner",
      "FREE Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "24 to 48 hours TAT",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Elite",
    price: "$1,299",
    description: "Advanced dynamic site suitable for businesses wanting interactive tools and strong visual appeal.",
    features: [
      "Up to 15 Unique Pages Website",
      "Conceptual and Dynamic Website",
      "Mobile Responsive",
      "Online Reservation/Appointment Tool (Optional)",
      "Online Payment Integration (Optional)",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Striking Hover Effects",
      "Newsletter Subscription (Optional)",
      "Newsfeed Integration",
      "Social Media Integration",
      "Search Engine Submission",
      "5 Stock Photos",
      "3 Unique Banner Designs",
      "1 jQuery Slider Banner",
      "Complete W3C Certified HTML",
      "24 to 48 hours TAT",
      "Complete Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Corporate",
    price: "$1,999",
    description: "High-end corporate solution with custom development, unlimited revisions, and premium integrations.",
    popular: true, // Strong value for established businesses
    features: [
      "15 to 20 Pages Website",
      "Custom Made, Interactive, Dynamic & High End Design",
      "Custom WP (or) Custom PHP Development",
      "1 jQuery Slider Banner",
      "Up to 10 Custom Made Banner Designs",
      "10 Stock Images",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content Management System (CMS)",
      "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional)",
      "Mobile Responsive",
      "Free Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete W3C Certified HTML",
      "Industry Specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Business",
    price: "$3,299",
    description: "Comprehensive business package including 2D explainer video and advanced marketing/SEO features.",
    features: [
      "15 to 20 Pages Website",
      "15 Seconds 2D Explainer Video",
      "Voice-Over & Sound Effects",
      "Professional Script Writing",
      "Storyboard",
      "SEO Meta Tags",
      "Custom Made, Interactive, Dynamic & High End Design",
      "Custom WP (or) Custom PHP Development",
      "1 jQuery Slider Banner",
      "Up to 10 Custom Made Banner Designs",
      "10 Stock Images",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content Management System (CMS)",
      "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional)",
      "Mobile Responsive",
      "Free Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete W3C Certified HTML",
      "Industry Specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Automated/Interactive Conferencing Portal",
    price: "$6,999",
    description: "Specialized LMS-style portal with video conferencing, gamification, and full automation tools.",
    features: [
      "Up to 20 Stock Images",
      "20 Unique Banner Designs",
      "Unlimited Page Website",
      "Custom Content Management System (CMS)",
      "Unique Pages And UI Design",
      "Complete Custom Development",
      "Process Automation Tools",
      "Newsfeed Integration",
      "Social Media Plugins Integration",
      "JQuery Slider",
      "Search Engine Submission",
      "Free Google Friendly Sitemap",
      "Custom Email Addresses",
      "Social Media Page Designs (Facebook, Twitter, Instagram)",
      "Complete W3C Certified HTML",
      "Complete Deployment 100%",
      "Automated Course Creation",
      "Video Conferencing",
      "Skills/Certification Tracking",
      "Mobile Learning",
      "Asynchronous Learning",
      "CRM Features",
      "Gamification",
      "Social Learning/Message Boards",
      "Motivational Triggers",
      "Forums And Webinars",
      "E-commerce And Subscriptions",
      "Online Course Booking",
      "Excellent Reporting",
      "Invoicing Integration",
      "Financial Integrations",
      "Student Information management",
      "Automated communications",
      "Learning Management System",
      "Quick And Easy Course Scheduling",
      "Reporting And Data Analysis",
      "Assessment Management & Live Feedback",
      "Gradebooks",
      "Quick User Integration",
      "Easy Payment Methods",
      "Online Communities & Social Engagement",
      "Curation of Resources And Adding Own Resources",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Real Estate Platform",
    price: "$8,999",
    description: "Tailored real estate platform with MLS integration, advanced tools, performance optimization, and investor focus.",
    features: [
      "Unlimited Page Website",
      "Custom Made, Interactive, Dynamic & High End Design",
      "Custom PHP Development",
      "Unlimited Revisions",
      "Special Hover Effects",
      "CRM and social tracking integration",
      "Google Analytics integration",
      "Chat bot and chat widgets",
      "Capture form integration",
      "Diverse API integrations",
      "Mobile Responsive Design",
      "Voiced for commercial real estate stakeholders and accredited investors",
      "Mission, vision, and principles/values statements",
      "Includes headings, subheadings, and capture form copy",
      "Appealing, tasteful, and actionable CTAs",
      "Live site proofing and review",
      "Optimize image formats, sizes, and compression",
      "Minimize and defer CSS and JavaScript",
      "Site speed optimization and monitoring",
      "Integrated graphic design of site elements",
      "Premium royalty-free imagery",
      "Logo update or redesign",
      "Introductory and social videos",
      "Multiple listing services access",
      "Live search",
      "Detailed listing",
      "Calendar Tool",
      "Calculator for calculating house cost, etc.",
      "Buyer/Seller/Tenant profile automation & management (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional)",
      "Search Engine Submission",
      "Complete W3C Certified HTML",
      "Industry Specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Custom CRM/ERP Portal",
    price: "$14,499",
    description: "Enterprise-grade custom CRM/ERP solution with full modules for sales, HR, finance, analytics, and integrations.",
    features: [
      "Unlimited Page Website",
      "Unique Pages and UI Design",
      "Complete Custom Development",
      "Newsfeed Integration",
      "CRM (Customer Relation Management System)",
      "Performance and analytics",
      "Customization of Personal Details",
      "Process management",
      "Sales Automation",
      "Team Collaboration",
      "Marketing Automation",
      "Security",
      "Integrations",
      "Mobile Notifications",
      "Sales Reports",
      "Trend Analytics",
      "Forecasting",
      "Territory Management",
      "Account Management",
      "Event Integration",
      "Advanced Data Security",
      "Opportunity Management",
      "Sales Forecasting",
      "Call/Video Logging",
      "Quotes",
      "Contracts",
      "Document Library",
      "Case Management",
      "Analytics and Dashboards",
      "Lead Management",
      "Resource Management",
      "Analytics",
      "Web Intelligence",
      "Automated Emails, Invoices & Estimates",
      "Automated Split invoicing",
      "Automated Combine invoices",
      "Invoice templates",
      "Financial Reports",
      "Generate extremely detailed reports for your sales and services",
      "Generate automated sales reports",
      "Core Modules: Human Resources, Integration, Business Intelligence, Sales/Marketing, Finance",
      "Core Features: Reporting, Accounting, Tracking and Visibility",
      "Centralized Modules: ERP Database, Human Resources Management, Business Process Management",
      "Enterprise Analytics, Business Intelligence",
      "Integrations (Manufacturing optional)",
      "Accounting, Distribution, Business Intelligence, Insights, Standardization, Procurement",
      "Reporting and Analytics, Forecasting, Projection",
      "Enterprise-wide integration, Real-Time Operations",
      "Advanced Admin Features 2.0",
      "User Signup/Login Functionalities",
      "Advanced User Features",
      "User Profile Management",
      "General Configuration Features",
      "Complete W3C Certified HTML",
      "Complete Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Social Media Platform",
    price: "$14,999",
    description: "Full-featured custom social network with user profiles, feeds, chat, notifications, and explainer video.",
    features: [
      "15 Seconds 2D Explainer Video",
      "Voice Over & Sound Effects",
      "Professional Script Writing",
      "Storyboard",
      "SEO Meta Tags",
      "Unlimited Pages Social Media Platform Website",
      "Custom Made, Interactive, Dynamic & High End Design",
      "Custom PHP Development",
      "1 jQuery Slider Banner",
      "Up to 10 Custom Made Banner Designs",
      "10 Stock Images",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content Management System (CMS)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Simple and Interactive Interface",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Social authorization for Users",
      "User Profile Management",
      "User Profile Customization",
      "Admin Profile Management",
      "Admin Authorization",
      "Analytics",
      "Send Friend Request/ Follow Request",
      "Push notification module",
      "In Web Chat Module",
      "In Web Advertisements",
      "Third Party Integrations",
      "Provide Rich Text Editors",
      "Easy Search",
      "Status update",
      "Post likes",
      "Post creation",
      "Easy Network Building",
      "Live Feed News and Content Sharing",
      "Social notifications",
      "Privacy and Security",
      "Live Feeds of Social Networks integration (Optional)",
      "Mobile Responsive",
      "Free Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete W3C Certified HTML",
      "Industry Specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "Free Add-Ons: Free Logo with Unlimited Revisions and Unlimited Concepts",
      "Free Complete Business Stationery Designs",
      "Free Social Media Platform Designs",
      "Free 12 Months of Technical Support",
    ],
  },
],

"E-commerce Development": [
  {
    name: "Basic",
    price: "$799",
    description: "Solid entry-level custom e-commerce store to launch your online shop quickly with essential sales tools.",
    features: [
      "Custom Designed Homepage (1x Concept)",
      "5 Custom Designed Inner Pages",
      "Up to 50 Products",
      "Up to 7 Categories",
      "Content Management System",
      "Sales & Inventory Management",
      "Mini Shopping Cart Integration",
      "Payment Gateway Integration",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "Easy Product Search",
      "5 Premium Stock Photos",
      "2 Promotional Banners",
      "Interactive jQuery Slider",
      "Cross Platform Responsive Compatibility",
      "Cross Browser Compatibility",
      "W3C Certified HTML",
      "Google Friendly Sitemap",
      "Complete Deployment",
      "30 Days Free Maintenance",
      "How-To-Use Training Manual for CMS",
      "Industry Specified Team of Expert Designers and Developers",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "100% Ownership Rights",
      "Complete Brand Identity – Additional $199",
      "Live Chat/Bot Chat Integration – Additional $249",
    ],
  },
  {
    name: "Plus",
    price: "$1,299",
    description: "Enhanced package for growing stores with more products, customer features, and SEO readiness.",
    popular: true,
    features: [
      "Custom Designed Homepage (2x Concepts)",
      "10 Custom Designed Inner Pages",
      "Interactive and Dynamic Website Design",
      "Up to 400 Products",
      "Up to 10 Categories",
      "15 Premium Stock Photos",
      "8 Promotional Banners",
      "1 Landing Page Design",
      "Interactive jQuery Slider",
      "Customer Login/Signup Area",
      "Complete Database Creation",
      "Live Chat/Bot Chat Integration (Optional)",
      "Shipping Merchant Integration",
      "Drop Shipping Integration (Optional)",
      "Content Management System",
      "Sales & Inventory Management",
      "Product Offers (Wish-list, Discount Options, Coupon Codes)",
      "Product Ratings & Reviews",
      "Easy Product Search",
      "Product Sorting (Newest, Featured, Popular, Best Seller)",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "3rd Party API Integration",
      "Customized Filters for Refined Search",
      "SEO Friendly Coding (Meta Tags, Titles, Descriptions, Keywords, W3C Compliant)",
      "On-Page SEO Configuration",
      "Search Engine Indexing (Google, Yahoo, Bing)",
      "Cross Platform Responsive Compatibility",
      "Cross Browser Compatibility",
      "Fast Load Time",
      "Security Plugins",
      "W3C Certified HTML",
      "Google Friendly Sitemap",
      "Complete Deployment",
      "5 Business Email Addresses",
      "90 Days Free Maintenance",
      "How-To-Use Training Manual for CMS",
      "Industry Specified Team of Expert Designers and Developers",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "100% Ownership Rights",
      "Multi-Currency Support – Additional $249",
      "Complete Brand Identity – Additional $199",
    ],
  },
  {
    name: "Prime",
    price: "$1,999",
    description: "Advanced mid-tier solution with high product limits, guest checkout, hosting/domain included, and strong SEO/marketing tools.",
    features: [
      "Custom Designed Homepage (3x Concepts)",
      "20 Custom Designed Inner Pages",
      "Interactive and Dynamic Website Design",
      "Up to 1000 Products",
      "Up to 20 Categories",
      "25 Premium Stock Photos",
      "15 Promotional Banners",
      "2 Landing Pages Design",
      "Interactive jQuery Slider",
      "Customer Login/Signup Area",
      "Complete Database Creation",
      "Live Chat/Bot Chat Integration (Optional)",
      "Shipping Merchant Integration",
      "Multi-Currency Support (Optional)",
      "Drop Shipping Integration (Optional)",
      "Content Management System",
      "Sales & Inventory Management",
      "Manage Orders (Track Order, Billing History, Order Status, Automated Invoicing)",
      "Product Offers (Wish-list, Discount Options, Coupon Codes)",
      "Multiple Product Variations (Color, Size, Quantity, etc.)",
      "Intelligent Search System with Filtering Options",
      "Product Sorting (Newest, Featured, Popular, Best Seller)",
      "Product Ratings & Reviews",
      "Easy Product Search",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Guest Checkout",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "3rd Party API Integration",
      "1 Year Free Hosting",
      "1 Year Free Domain Registration",
      "SEO Friendly Coding (Meta Tags, Titles, Descriptions, Keywords, W3C Compliant)",
      "On-Page SEO Configuration",
      "Search Engine Indexing (Google, Yahoo, Bing)",
      "Cross Platform Responsive Compatibility",
      "Cross Browser Compatibility",
      "Email Marketing Campaigns",
      "Fast Load Time",
      "Security Plugins",
      "W3C Certified HTML",
      "Google Friendly Sitemap",
      "Google Analytic Installation",
      "Google Webmaster Tool",
      "Complete Deployment",
      "5 Business Email Addresses",
      "180 Days Free Maintenance",
      "How-To-Use Training Manual for CMS",
      "Industry Specified Team of Expert Designers and Developers",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "100% Ownership Rights",
      "Marketplace Development – Additional $749",
      "30 Seconds Explainer Video – Additional $349",
    ],
  },
  {
    name: "Advance",
    price: "$2,999",
    description: "Robust expansion on Prime with higher product capacity and similar premium features for scaling businesses.",
    features: [
      "Custom Designed Homepage (3x Concepts)",
      "20 Custom Designed Inner Pages",
      "Interactive and Dynamic Website Design",
      "Up to 1000–1500 Products",
      "Up to 20 Categories",
      "25 Premium Stock Photos",
      "15 Promotional Banners",
      "2 Landing Pages Design",
      "Interactive jQuery Slider",
      "Customer Login/Signup Area",
      "Complete Database Creation",
      "Live Chat/Bot Chat Integration (Optional)",
      "Shipping Merchant Integration",
      "Multi-Currency Support (Optional)",
      "Drop Shipping Integration (Optional)",
      "Content Management System",
      "Sales & Inventory Management",
      "Manage Orders (Track Order, Billing History, Order Status, Automated Invoicing)",
      "Product Offers (Wish-list, Discount Options, Coupon Codes)",
      "Multiple Product Variations (Color, Size, Quantity, etc.)",
      "Intelligent Search System with Filtering Options",
      "Product Sorting (Newest, Featured, Popular, Best Seller)",
      "Product Ratings & Reviews",
      "Easy Product Search",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Guest Checkout",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "3rd Party API Integration",
      "1 Year Free Hosting",
      "1 Year Free Domain Registration",
      "SEO Friendly Coding (Meta Tags, Titles, Descriptions, Keywords, W3C Compliant)",
      "On-Page SEO Configuration",
      "Search Engine Indexing (Google, Yahoo, Bing)",
      "Cross Platform Responsive Compatibility",
      "Cross Browser Compatibility",
      "Email Marketing Campaigns",
      "Fast Load Time",
      "Security Plugins",
      "W3C Certified HTML",
      "Google Friendly Sitemap",
      "Google Analytic Installation",
      "Google Webmaster Tool",
      "Complete Deployment",
      "5 Business Email Addresses",
      "180 Days Free Maintenance",
      "How-To-Use Training Manual for CMS",
      "Industry Specified Team of Expert Designers and Developers",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "100% Ownership Rights",
      "Marketplace Development – Additional $749",
      "30 Seconds Explainer Video – Additional $349",
    ],
  },
  {
    name: "Business",
    price: "$4,499",
    description: "High-end unlimited package with advanced UI/UX, bulk tools, rewards, and long-term hosting for serious e-commerce operations.",
    popular: true,
    features: [
      "Custom Designed Homepage (6x Concepts)",
      "Unlimited Custom Designed Inner Pages",
      "Custom Made, Interactive, Dynamic & User Friendly Design",
      "High End UI/UX",
      "Custom Coding & Development",
      "Marketplace Development (Optional)",
      "Content Management System",
      "Sales & Inventory Management",
      "Unlimited Products",
      "Unlimited Categories",
      "Unlimited Premium Stock Photos",
      "Unlimited Promotional Banners",
      "2 Landing Pages Design",
      "Interactive jQuery Slider",
      "Cross Platform Responsive Compatibility",
      "Product Details Page Design",
      "Bulk CSV Products Upload",
      "Product Return Management System",
      "Reward Pointing System",
      "Custom Calculators",
      "Product Offers (Wish-list, Discount Options, Coupon Codes)",
      "Multiple Product Variations (Color, Size, Quantity, etc.)",
      "Intelligent Search System with Filtering Options",
      "Product Sorting (Newest, Featured, Popular, Best Seller)",
      "Shipping Merchant Integration",
      "Drop Shipping Integration (Optional)",
      "Customer Login/Signup Area",
      "Complete Database Creation",
      "Full Shopping Cart Integration",
      "Product Ratings & Reviews",
      "Automated Emails",
      "Automated Reminders",
      "Email Marketing Campaigns",
      "Tell a Friend Feature",
      "Guest Checkout",
      "Shipping Labels",
      "News & Promotions",
      "Downloadable Items (eBooks, PDFs, Podcast, Videos)",
      "Easy Product Search",
      "Payment Gateway Integration",
      "Multi-Currency Support",
      "Live Chat/Bot Chat Integration (Optional)",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "Social Media Live Feeds Widget (Facebook, Instagram, Pinterest)",
      "3rd Party API Integration",
      "Signup Automated Email Authentication",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Engine Indexing (Google, Yahoo, Bing)",
      "Module-Wise Architecture",
      "Extensive Admin Panel",
      "404 Redirect",
      "XML Sitemap",
      "Parallax Scrolling",
      "Fast Load Time",
      "Security Plugins",
      "5 Years Free Hosting",
      "5 Years Free Domain Registration",
      "SEO Friendly Coding (Meta Tags, Titles, Description, Keywords)",
      "On-Page SEO Configuration",
      "Google Friendly Sitemap",
      "Google Analytic Installation",
      "Google Webmaster Tool",
      "W3C Certified HTML",
      "Cross Browser Compatible",
      "Complete Deployment",
      "48-72 Hours Turnaround Time",
      "Unlimited Business Email Addresses",
      "1 Year Free Maintenance",
      "Industry Specified Team of Expert Designers and Developers",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "100% Ownership Rights",
      "Professional Content/Copywriting – Additional $1,000 (Up to 20 Pages, $50/Page)",
      "Search Engine Optimization (3 Months – 50 Keywords) – Additional $1,350",
    ],
  },
  {
    name: "Automated/Interactive",
    price: "$7,999.99",
    description: "Sophisticated automated e-commerce with real-time inventory, ML-driven supply chain, barcode support, and advanced analytics.",
    features: [
      "Unlimited Page Website",
      "Custom Content Management System (CMS)",
      "Unique Pages and UI Design",
      "Complete Custom Development",
      "Process Automation Tools",
      "Newsfeed Integration",
      "Social Media Plugins Integration",
      "Up to 40 Stock Images",
      "10 Unique Banner Designs",
      "JQuery Slider",
      "Search Engine Submission",
      "Free Google Friendly Sitemap",
      "FREE 5 Years Hosting",
      "Custom Email Addresses",
      "Social Media Page Designs (Facebook, Twitter, Instagram)",
      "Complete W3C Certified HTML",
      "Complete Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "Automated Inventory/Shipping/Supplier Module",
      "Real-Time Stock Levels & Low Inventory Notifications",
      "Purchase Orders Generation",
      "Suppliers Integration (API Needed)",
      "Shipper Integration (API Needed)",
      "Order Management",
      "LOT Numbers & Expire Date Tracking",
      "Transfer Stock Between Warehouses (API Needed)",
      "Receive/Fulfill Stock by Warehouse (API Needed)",
      "Stock Management",
      "Actionable Insights & Real-Time Visibility",
      "Inventory Opportunities",
      "Advanced Features (API Needed for Suppliers/Warehouse)",
      "Supplier Communication & Purchasing Requests",
      "Invoice/Payment Documentation",
      "Machine Learning for Supply Chain Planning",
      "Machine Learning for Warehouse Management",
      "NLP for Data Cleansing",
      "Automated Invoices & Estimates",
      "Automated Split/Combine Invoices",
      "Invoice Templates",
      "Automated Barcode Scanning",
      "Locations and Zones Management",
      "Customer Accounts",
      "Performance and Analytics",
      "Customization of Personal Details",
      "Process Management",
      "Sales Automation",
      "Team Collaboration",
      "Marketing Automation",
      "Security",
      "Integrations",
      "Mobile Notifications",
      "Sales Reports",
      "Trend Analytics",
      "Forecasting",
      "Territory Management",
      "Account Management",
      "Event Integration",
      "Advanced Data Security",
      "Purchase Orders",
      "Partial Orders Fulfill & Backordering",
      "Financial Reports & Detailed Filtering",
    ],
  },
  {
    name: "Market Place Platform",
    price: "$13,499",
    description: "Full multi-vendor marketplace with advanced seller/buyer tools, revenue models, loyalty features, and long-term maintenance.",
    features: [
      "Unlimited Page Website",
      "Custom Content Management System (CMS)",
      "Unique Pages and UI Design",
      "Complete Custom Development",
      "Process Automation Tools",
      "Newsfeed Integration",
      "Social Media Plugins Integration",
      "Unlimited Stock Images",
      "10 Unique Banner Designs",
      "JQuery Slider",
      "Search Engine Submission",
      "Free Google Friendly Sitemap",
      "Custom Email Addresses",
      "Social Media Page Designs (Facebook, Twitter, Instagram, etc.)",
      "Complete W3C Certified HTML",
      "Complete Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "Automated Inventory/Shipping/Supplier Module",
      "Real-Time Inventory Management",
      "Low Inventory Notifications & Purchase Orders",
      "Suppliers/Shipper Integration (API Needed)",
      "Order Management",
      "LOT & Expire Date Tracking",
      "Warehouse Stock Transfer/Receive/Fulfill (API Needed)",
      "Stock Management",
      "Actionable Insights & Real-Time Visibility",
      "Export Reports",
      "Wallet/Vault for Seller Revenue Disbursement",
      "AirBnB-Style Process Management",
      "Guest & House Owner Profile Management",
      "Advanced Features (API Needed)",
      "Supplier Communication & Requests",
      "Invoice/Payment Documentation",
      "Machine Learning for Supply Chain & Warehouse",
      "NLP for Data Robustness",
      "Automated Invoices & Estimates",
      "Automated Split/Combine Invoices",
      "Invoice Templates",
      "Automated Barcode Scanning",
      "Locations and Zones",
      "Customer Accounts",
      "Performance & Analytics",
      "Customization",
      "Process Management",
      "Sales/Marketing Automation",
      "Team Collaboration",
      "Security & Integrations",
      "Mobile/Email Notifications",
      "Advanced Ecommerce Marketplace Features",
      "Inventory Management",
      "Advanced Admin/User Features",
      "Dashboard & Analytics for Super Admin",
      "Seller/Shipping Distribution",
      "Seller/Buyer/User Profile Management",
      "Drop Shipping Feature Integration",
      "Barcode Scanning Module",
      "General Configuration Features",
      "Revenue Models Module",
      "Featured Products",
      "Sponsor Advertisement Management",
      "Google Advertisements",
      "Flash Sales Module",
      "Loyalty Rewards Module",
      "Coupon Code Module",
      "In-Web Messaging (Seller-Buyer/Admin)",
      "Configure Parameters/Verification Process",
      "Sales Reports",
      "Trend Analytics",
      "Forecasting",
      "Territory Management",
      "Account Management",
      "Event Integration",
      "Advanced Data Security",
      "Purchase Orders",
      "Partial Orders Fulfill & Backordering",
      "Financial Reports & Detailed Filtering",
      "12 Months Free Maintenance",
    ],
  },
],
"Shopify Packages": [
  {
    name: "Basic",
    price: "$649",
    description: "Affordable entry-level Shopify setup for launching a simple, professional online store quickly.",
    features: [
      "Customized Design",
      "Up to 50 Products",
      "Content Management System (CMS)",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Easy Product Search",
      "Dedicated Designer & Developer",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Plus",
    price: "$1,249",
    description: "Enhanced Shopify package with higher product limits, reviews, and promotional tools for growing stores.",
    popular: true,
    features: [
      "Customized Design",
      "Up to 500 Products",
      "Content Management System (CMS)",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Easy Product Search",
      "Product Reviews",
      "5 Promotional Banners",
      "Team of Expert Designers & Developers",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Prime",
    price: "$1,999",
    description: "Mid-tier Shopify solution with unlimited products, multiple integrations, and strong branding elements for established sellers.",
    features: [
      "20 Custom Designed Inner Pages",
      "5 Custom Logo Designs",
      "CMS / Backend Administrative System",
      "Unlimited Products with Unlimited Categories",
      "Unlimited Revisions",
      "Custom Shopping Cart Integration",
      "Multiple Payment Module Integration",
      "Multiple Shipping Module Integration",
      "Product Ratings & Reviews",
      "Sales & Inventory Management System",
      "Multiple Currency Support",
      "Customer Login Area (Sign-Up & Sign-In)",
      "Mobile Responsive",
      "Social Media Designs (Facebook, Twitter, YouTube)",
      "Dedicated Team of Expert Designers & Developers",
      "Dedicated Project Manager",
      "Newsletter Subscription",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Advance",
    price: "$2,999",
    description: "Advanced Shopify build with high customization, SEO/marketing tools, hosting/domain included, and scalable features.",
    features: [
      "Custom Designed Homepage (3x Concepts)",
      "Unlimited Pages Website with Unique Design",
      "Interactive and Dynamic Website Design",
      "Up to 250–1000 Products",
      "Up to 20 Categories",
      "25 Premium Stock Photos",
      "15 Promotional Banners",
      "2 Landing Pages Design",
      "Interactive jQuery Slider",
      "Customer Login/Signup Area",
      "Complete Database Creation",
      "Live Chat/Bot Chat Integration (Optional)",
      "Shipping Merchant Integration",
      "Multi-Currency Support (Optional)",
      "Dropshipping Integration (Optional)",
      "Content Management System",
      "Sales & Inventory Management",
      "Manage Orders (Track Order, Billing History, Order Status, Automated Invoicing)",
      "Product Offers (Wish-list, Discount Options, Coupon Codes)",
      "Multiple Product Variations (Color, Size, Quantity, etc.)",
      "Intelligent Search System with Filtering Options",
      "Product Sorting (Newest, Featured, Popular, Best Seller)",
      "Product Ratings & Reviews",
      "Easy Product Search",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Guest Checkout",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "3rd Party API Integration",
      "1 Year Free Hosting",
      "1 Year Free Domain Registration",
      "SEO Friendly Coding (Meta Tags, Titles, Descriptions, Keywords, W3C Compliant)",
      "On-Page SEO Configuration",
      "Search Engine Indexing (Google, Yahoo, Bing)",
      "Cross Platform Responsive Compatibility",
      "Cross Browser Compatibility",
      "Email Marketing Campaigns",
      "Fast Load Time",
      "Security Plugins",
      "W3C Certified HTML",
      "Google Friendly Sitemap",
      "Google Analytic Installation",
      "Google Webmaster Tool",
      "Complete Deployment",
      "5 Business Email Addresses",
      "180 Days Free Maintenance",
      "How-To-Use Training Manual for CMS",
      "Industry Specified Team of Expert Designers and Developers",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "100% Ownership Rights",
      "Marketplace Development – Additional $749",
      "30 Seconds Explainer Video – Additional $349",
    ],
  },
  {
    name: "Business",
    price: "$4,499",
    description: "Premium unlimited Shopify package with high-end UI/UX, advanced tools, long-term hosting, and enterprise-like features for scaling operations.",
    popular: true,
    features: [
      "Custom Designed Homepage (6x Concepts)",
      "Unlimited Custom Designed Inner Pages",
      "Custom Made, Interactive, Dynamic & User Friendly Design",
      "High End UI/UX",
      "Custom Coding & Development",
      "Marketplace Development (Optional)",
      "Content Management System",
      "Sales & Inventory Management",
      "Unlimited Products",
      "Unlimited Categories",
      "Unlimited Premium Stock Photos",
      "Unlimited Promotional Banners",
      "2 Landing Pages Design",
      "Interactive jQuery Slider",
      "Cross Platform Responsive Compatibility",
      "Product Detail Page Design",
      "Bulk CSV Products Upload",
      "Product Return Management System",
      "Reward Pointing System",
      "Custom Calculators",
      "Product Offers (Wish-list, Discount Options, Coupon Codes)",
      "Multiple Product Variations (Color, Size, Quantity, etc.)",
      "Intelligent Search System with Filtering Options",
      "Product Sorting (Newest, Featured, Popular, Best Seller)",
      "Shipping Merchant Integration",
      "Dropshipping Integration (Optional)",
      "Customer Login/Signup Area",
      "Complete Database Creation",
      "Full Shopping Cart Integration",
      "Product Ratings & Reviews",
      "Automated Emails",
      "Automated Reminders",
      "Email Marketing Campaigns",
      "Tell a Friend Feature",
      "Guest Checkout",
      "Shipping Labels",
      "News & Promotions",
      "Downloadable Items (eBooks, PDFs, Podcast, Videos)",
      "Easy Product Search",
      "Payment Gateway Integration",
      "Multi-Currency Support",
      "Live Chat/Bot Chat Integration (Optional)",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "Social Media Live Feeds Widget (Facebook, Instagram, Pinterest)",
      "3rd Party API Integration",
      "Signup Automated Email Authentication",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Engine Indexing (Google, Yahoo, Bing)",
      "Module-Wise Architecture",
      "Extensive Admin Panel",
      "404 Redirect",
      "XML Sitemap",
      "Parallax Scrolling",
      "Fast Load Time",
      "Security Plugins",
      "5 Years Free Hosting",
      "5 Years Free Domain Registration",
      "SEO Friendly Coding (Meta Tags, Titles, Description, Keywords)",
      "On-Page SEO Configuration",
      "Google Friendly Sitemap",
      "Google Analytic Installation",
      "Google Webmaster Tool",
      "W3C Certified HTML",
      "Cross Browser Compatible",
      "Complete Deployment",
      "48-72 Hours Turnaround Time",
      "Unlimited Business Email Addresses",
      "1 Year Free Maintenance",
      "Industry Specified Team of Expert Designers and Developers",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "100% Ownership Rights",
      "Professional Content/Copywriting – Additional $1,000 (Up to 20 Pages, $50/Page)",
      "Search Engine Optimization (3 Months – 50 Keywords) – Additional $1,350",
    ],
  },
],
"Web Maintenance Packages": [
  {
    name: "Basic",
    price: "$99",
    description: "Affordable entry-level monthly plan with essential hosting, security, and light maintenance for small or personal sites.",
    features: [
      "Free Domain",
      "Website Hosting",
      "SSL Certificate Integration",
      "Disk Space: 10GB",
      "Email Accounts: 10",
      "Monthly Bandwidth: Unlimited",
      "CPUs: 1",
      "Memory: 1024 MB",
      "Database Backup/Restore",
      "Strategic Assistance",
      "Plugins Integration",
      "Technical Optimization",
      "Site Structure Optimization",
      "100% Satisfaction Guarantee",
    ],
  },
  {
    name: "Enterprise",
    price: "$199",
    description: "Upgraded plan with more resources, SEO tools, and advanced support for growing or professional websites needing better performance and visibility.",
    popular: true,
    features: [
      "2 Free Domains",
      "Website Hosting",
      "Strategic Assistance",
      "On-Page SEO",
      "Google Analytics Integration",
      "Webmaster Integration",
      "Plugins Integration",
      "Technical Optimization",
      "Site Structure Optimization",
      "SSL Certificate Integration",
      "Disk Space: 35GB",
      "Email Accounts: 0",
      "Monthly Bandwidth: Unlimited",
      "CPUs: 2",
      "Memory: 2048 MB",
      "Database Backup/Restore",
      "FTP Users: 2",
      "100% Satisfaction Guarantee",
    ],
  },
],
"3D Animation": [
  {
    name: "Basic 3D",
    price: "$2,995",
    description: "Entry-level 30-second custom 3D explainer with unlimited revisions—perfect for startups needing quick, professional product demos or intros.",
    features: [
      "30-Second Duration in HD 1080p",
      "Unlimited Revisions & Concepts",
      "Professional Script",
      "Concept and Storyboards",
      "3D Modeling",
      "Texturing",
      "Rigging",
      "Animation",
      "Lighting",
      "Camera Setting",
      "Rendering",
      "Compositing and Special VFX",
      "Music and Foley",
      "Custom Setting, 2 Characters & Graphics",
      "Animation Effects & Visualization",
      "Voice Over – All Accents (Male/Female)",
      "Editing and Final Output",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "Money Back Guarantee",
    ],
  },
  {
    name: "Standard 3D",
    price: "$4,995",
    description: "Balanced 60-second 3D animation with double the duration and same unlimited revisions—ideal for detailed explanations or marketing videos.",
    popular: true,
    features: [
      "60-Second Duration in HD 1080p",
      "Unlimited Revisions & Concepts",
      "Professional Script",
      "Concept and Storyboards",
      "3D Modeling",
      "Texturing",
      "Rigging",
      "Animation",
      "Lighting",
      "Camera Setting",
      "Rendering",
      "Compositing and Special VFX",
      "Music and Foley",
      "Custom Setting, 2 Characters & Graphics",
      "Animation Effects & Visualization",
      "Voice Over – All Accents (Male/Female)",
      "Editing and Final Output",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "Money Back Guarantee",
    ],
  },
  {
    name: "Premium 3D",
    price: "$6,995",
    description: "Extended 120-second premium 3D video with more characters and complexity—great for in-depth storytelling, product tours, or enterprise demos.",
    features: [
      "120-Second Duration in HD 1080p",
      "Unlimited Revisions & Concepts",
      "Professional Script",
      "Concept and Storyboards",
      "3D Modeling",
      "Texturing",
      "Rigging",
      "Animation",
      "Lighting",
      "Camera Setting",
      "Rendering",
      "Compositing and Special VFX",
      "Music and Foley",
      "Custom Setting, 4 Characters & Graphics",
      "Animation Effects & Visualization",
      "Voice Over – All Accents (Male/Female)",
      "Editing and Final Output",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "Money Back Guarantee",
    ],
  },
],
"Logo Design": [
  {
    name: "Basic Package",
    price: "$50",
    description: "Ultra-budget entry-level logo for quick needs or testing ideas—ideal for solopreneurs or side projects.",
    features: [
      "2 Custom Logo Design Concepts by 2 Designers",
      "2 Revisions",
      "48 to 72 Hours Turnaround Time",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Basic Plus Package",
    price: "$70",
    description: "Enhanced starter logo with more concepts, revisions, stationery basics, and file variety—great for small businesses starting out.",
    features: [
      "4 Logo Design Concepts",
      "Up to 8 Revisions",
      "2 Dedicated Designers",
      "Stationery Design (Business Card)",
      "Color Options",
      "Grayscale Format",
      "Free Icon",
      "24 to 48 Hours Turnaround Time",
      "All File Formats (PNG, JPEG, PDF)",
      "100% Unique Design Guarantee",
      "100% Ownership Rights",
    ],
  },
  {
    name: "Startup Pro Package",
    price: "$125",
    description: "Solid startup-friendly package with unlimited revisions, full stationery, and website discount—perfect for early-stage ventures.",
    features: [
      "6 Logo Design Concepts",
      "Unlimited Revisions",
      "3 Award-Winning Designers",
      "Complete Stationery Design (Business Card, Letterhead, Envelope)",
      "Color Options",
      "Grayscale Format",
      "24 to 48 Hours Turnaround Time",
      "15% Off on Website Order",
      "All File Formats (AI, PSD, EPS, PNG, JPG, PDF, PES)",
      "100% Ownership Rights",
      "100% Unique Design Guarantee",
    ],
  },
  {
    name: "Professional Business Package",
    price: "$150",
    description: "Professional-level logo with social media extras and unlimited revisions—strong choice for service-based or local businesses.",
    popular: true,
    features: [
      "8 Logo Design Concepts",
      "Unlimited Revisions",
      "3 Award-Winning Designers",
      "Complete Stationery Design (Business Card, Letterhead, Envelope)",
      "Icon Design",
      "Social Media Designs (Any 2: Facebook, YouTube, Instagram, LinkedIn, etc.)",
      "Color Options",
      "Grayscale Format",
      "24 to 48 Hours Turnaround Time",
      "15% Off on Website Order",
      "All File Formats (AI, PSD, EPS, PNG, JPG, PDF, PES)",
      "100% Ownership Rights",
      "100% Unique Design Guarantee",
    ],
  },
  {
    name: "Business Professional Pro",
    price: "$199",
    description: "Expanded pro package with unlimited concepts, full stationery, brochure, and complete social designs—ideal for growing brands.",
    features: [
      "Unlimited Logo Design Concepts",
      "Unlimited Revisions",
      "5 Dedicated Award-Winning Designers",
      "Complete Stationery Design (Business Card, Letterhead, Folder, Envelopes)",
      "2 Page Corporate Brochure",
      "Complete Social Media Designs (Facebook, LinkedIn, Instagram, YouTube)",
      "Grayscale Format",
      "Icon Design",
      "24 to 48 Hours Turnaround Time",
      "20% Off on Website Order",
      "All File Formats (AI, PSD, EPS, PNG, JPG, PDF, PES)",
      "100% Ownership Rights",
      "100% Unique Design Guarantee",
    ],
  },
  {
    name: "Business Plus",
    price: "$299",
    description: "Comprehensive plus package adding landing page design and extended social coverage—excellent for businesses ready to scale online.",
    popular: true,
    features: [
      "Unlimited Logo Design Concepts",
      "Unlimited Revisions",
      "6 Dedicated Award-Winning Designers",
      "Complete Stationery Design (Business Card, Letterhead, Folder, Envelopes)",
      "4 Page Corporate Brochure",
      "Business Web Landing Page Design",
      "Complete Social Media Designs (Facebook, LinkedIn, Instagram, YouTube, Pinterest, Reddit, etc.)",
      "Free Color Options",
      "Free Grayscale Format",
      "20% Off on Website Order",
      "24 Hours Turnaround Time",
      "All File Formats (AI, PSD, EPS, PNG, JPG, PDF, PES)",
      "100% Ownership Rights",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Business Pro Complete Branding",
    price: "$449",
    description: "All-in-one premium branding with animated logo, full collateral, and fast delivery—top choice for established brands wanting a complete identity.",
    features: [
      "Unlimited Logo Design Concepts",
      "Unlimited Revisions",
      "6 Dedicated Award-Winning Designers",
      "Complete Stationery Design (Business Card, Letterhead, Folder, Envelopes)",
      "4 Page Corporate Brochure",
      "Business Web Landing Page Design",
      "Animated Logo (2 Concepts, 5-10 Seconds Duration)",
      "Short Fitting Sound/Music Matching Brand Tone",
      "Animated Logo Files (MP4, MOV, GIF, PNG/PSD)",
      "Complete Social Media Designs (Facebook, LinkedIn, Instagram, YouTube, Pinterest, Reddit, etc.)",
      "Free Color Options",
      "Free Grayscale Format",
      "20% Off on Website Order",
      "24 Hours Turnaround Time",
      "All File Formats (AI, PSD, EPS, PNG, JPG, PDF, PES)",
      "100% Ownership Rights",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  // Existing packages preserved below for completeness/reference
  {
    name: "Basic Package",
    price: "$125.00",
    description: "Perfect entry-level option for new small businesses or simple logo refresh projects.",
    features: [
      "4 Unique Logo concepts",
      "1 Creative Designer",
      "48 hrs. Turnaround Time",
      "Unlimited Revisions",
      "Ownership Rights",
      "Unique Design Guarantee",
      "Satisfaction Guarantee",
      "Free Final Formats",
      "A.I, EPS, PSD, JPEG, PNG, TIFF, BMP & PDF",
      "Moneyback Guarantee*",
    ],
  },
  {
    name: "Startup Package",
    price: "$175.00",
    description: "Ideal for startups and growing businesses that want more concepts and free icon design.",
    features: [
      "6 Unique Logo concepts",
      "Free icon design",
      "2 Creative Designers",
      "48 hrs. Turnaround Time",
      "Unlimited Revisions",
      "Ownership Rights",
      "Unique Design Guarantee",
      "Satisfaction Guarantee",
      "Free Final Formats",
      "Moneyback Guarantee*",
      "A.I, EPS, PSD, JPEG, PNG, TIFF, BMP & PDF",
    ],
  },
  {
    name: "Professional Package",
    price: "$199.00",
    popular: true,
    description: "Best value for growing businesses wanting full branding support including business card design.",
    features: [
      "8 Logo concepts",
      "4 Creative Designers",
      "24-48 hrs. Turnaround Time",
      "Unlimited Revision",
      "Ownership Rights",
      "Unique Design Guarantee",
      "Satisfaction Guarantee",
      "Free Brand Consultation",
      "Moneyback Guarantee*",
      "Business Card, Letterhead, Envelope Design",
      "A.I, EPS, PSD, JPEG, PNG, TIFF, BMP & PDF",
    ],
  },
  {
    name: "Elite Package",
    price: "$245.00",
    description: "High-impact package with unlimited concepts and extra marketing materials for serious brands.",
    features: [
      "UNLIMITED Logo Design Concepts",
      "By 8 Award Winning Designers",
      "24-48 hrs. Turnaround Time",
      "Unlimited Revisions",
      "Stationary Design (Letterhead, Envelope, Business Cards)",
      "Icon Design",
      "Double Sided Flyer Design / Bi-Fold Brochure",
      "Free Email Signature",
      "Free Final Formats",
      "Ownership Rights",
      "Unique Design Guarantee",
      "Satisfaction Guarantee",
      "Moneyback Guarantee*",
    ],
  },
  {
    name: "Business Package",
    price: "$299.00",
    description: "Complete branding solution with unlimited concepts and full stationery design for established businesses.",
    features: [
      "UNLIMITED Logo Design Concepts",
      "By 8 Award Winning Designers",
      "24-48 hrs. Turnaround Time",
      "Unlimited Revisions",
      "Stationary Design (Letterhead, Envelope, Business Cards)",
      "Icon Design",
      "Double Sided Flyer Design / Bi-Fold Brochure",
      "Free Email Signature",
      "Free Final Formats",
      "Ownership Rights",
      "Unique Design Guarantee",
      "Satisfaction Guarantee",
      "Moneyback Guarantee*",
    ],
  },
  {
    name: "Gold Package",
    price: "$425.00",
    description: "Ultimate all-in-one package with unlimited concepts, website, banners, and full branding materials.",
    features: [
      "UNLIMITED Logo Design Concepts",
      "By 8 Award Winning Designers",
      "Icon Design",
      "24-48 hrs. Turnaround Time",
      "UNLIMITED Revisions",
      "Stationary Design (Letterhead, Envelope, Business Cards)",
      "Free Email Signature",
      "3 Page Custom Website",
      "2 Stock Photos",
      "2 Banner Designs",
      "jQuery Slider",
      "All Final Files Format",
      "Ownership Rights",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "Money Back Guarantee*",
    ],
  },
],
 

  "Lead Generation": [
    {
      name: "Starter Lead Package",
      price: "$699/month",
      description: "Perfect for testing and getting first consistent leads.",
      features: [
        "Up to $1,000 monthly ad spend (paid by you)",
        "Meta or Google Ads (your choice)",
        "5 professional ad creatives",
        "Basic landing page or lead form",
        "Targeting your local area only",
        "Lead tracking setup",
        "Weekly performance report",
        "Ad optimization twice per week",
        "Direct lead delivery (call/email)",
        "No long-term contract",
        "Pause or cancel anytime",
        "Full transparency",
        "Money back if no leads in 30 days",
      ],
    },
    {
      name: "Growth Lead Package",
      price: "$899/month",
      popular: true,
      description: "Most popular for steady monthly customer growth.",
      features: [
        "Up to $2,000 monthly ad spend (paid by you)",
        "Meta + Google Ads combined",
        "10 professional ad creatives",
        "Custom landing page with form",
        "Advanced local targeting",
        "Retargeting past visitors",
        "Lead tracking + call recording",
        "Twice weekly performance report",
        "Daily ad optimization",
        "Direct lead delivery + CRM option",
        "No long-term contract",
        "Pause or cancel anytime",
        "Full transparency",
        "Money back if no leads in 30 days",
      ],
    },
    {
      name: "Premium Lead Package",
      price: "$1,599/month",
      description: "Maximum leads for businesses ready to scale fast.",
      features: [
        "Up to $4,000 monthly ad spend (paid by you)",
        "Meta + Google + Organic boost",
        "15+ professional ad creatives",
        "High-converting custom landing page",
        "Hyper-local + competitor targeting",
        "Full retargeting + lookalike audiences",
        "Advanced tracking + analytics",
        "Daily performance report + call",
        "Real-time optimization",
        "Direct leads + appointment booking setup",
        "No long-term contract",
        "Pause or cancel anytime",
        "Full transparency",
        "Money back if no leads in 30 days",
      ],
    },
  ],

"SEO": [
  {
    name: "Local Starter SEO",
    price: "$399",
    description: "Great for new or small businesses starting to get found locally.",
    features: [
      "Google Business Profile optimization",
      "10 local citations built",
      "Basic keyword research (5 terms)",
      "On-page fixes (title, meta, headings)",
      "Review response template",
      "Monthly ranking report",
      "4 weeks of support",
      "One-time setup fee",
      "No monthly commitment",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
  {
    name: "Local Growth SEO",
    price: "$699",
    popular: true,
    description: "Best choice for most service businesses wanting steady leads.",
    features: [
      "Everything in Starter Package",
      "25+ local citations & cleanup",
      "Keyword research (10–15 terms)",
      "Full on-page SEO audit & fixes",
      "Review generation strategy",
      "Competitor analysis report",
      "Google Maps ranking focus",
      "Monthly progress call",
      "Ongoing tweaks for 3 months",
      "Dedicated project manager",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
  {
    name: "Local Premium SEO",
    price: "$999",
    description: "High-end package for dominating your local searches.",
    features: [
      "Everything in Growth Package",
      "50+ high-authority citations",
      "Advanced keyword research (20+ terms)",
      "Technical SEO audit & fixes",
      "Content suggestions for service pages",
      "Aggressive review building system",
      "Local link building (guest posts, directories)",
      "Bi-weekly performance calls",
      "Ongoing optimization for 6 months",
      "Expert team review",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
  {
    name: "Startup Plan",
    price: "$350/m",
    description: "Affordable entry-level monthly SEO for startups—focuses on foundational on-page, content, and initial off-page to build visibility.",
    features: [
      "Campaign Setup And Optimization",
      "Website Audit",
      "10 Pages Optimized",
      "15 Selected Keywords Targeting",
      "Keyword Research, Grouping & Mapping",
      "On-Page Optimization",
      "SEO Road Map",
      "Blog Creation",
      "Webpage Copywriting (3 pages, 350 words each)",
      "Title Tag Optimization (10 titles)",
      "Meta Description Optimization (10 descriptions)",
      "Meta Keyword Optimization (10 keywords)",
      "Domain Redirect Optimization (10 redirects)",
      "XML Sitemap Optimization",
      "Robots.txt Check",
      "URL Rewrites (10 rewrites)",
      "Broken Link Report",
      "Rich Snippet Recommendations",
      "Breadcrumbs",
      "Initial Off-Page SEO",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQs",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
    ],
  },
  {
    name: "Scaling Plan",
    price: "$700/m",
    popular: true,
    description: "Mid-tier monthly scaling SEO with deeper analysis, more keywords/pages, tracking, and consistent off-page—ideal for growing businesses.",
    features: [
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "35 Selected Keywords Targeting",
      "15 Pages Keyword Targeted",
      "Webpage Optimization",
      "Meta Tags Creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of Anchor Tags",
      "Tracking & Analysis",
      "Google Analytics Installation",
      "Google Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Monthly Reporting & Recommendations",
      "Email & Phone Support",
      "Off-Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQs",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
    ],
  },
  {
    name: "Venture Plan",
    price: "$1200/m",
    description: "Premium venture-level monthly SEO with extensive keywords/pages, advanced analysis, Google Places, and comprehensive off-page—suited for ambitious scaling.",
    features: [
      "Prior Analysis",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "60+ Selected Keywords Targeting",
      "30 Pages Keyword Targeted",
      "Webpage Optimization",
      "Meta Tags Creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of Anchor Tags",
      "Indexing Modifications",
      "Tracking & Analysis",
      "Google Places Inclusions",
      "Google Analytics Installation",
      "Google Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Monthly Reporting & Recommendations",
      "Email & Phone Support",
      "Off-Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQs",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
    ],
  },
],

"Social Media Marketing": [
  {
    name: "Startup SMM",
    price: "$299",
    description: "Budget-friendly startup package for launching on Facebook & Instagram with solid content and foundational strategy.",
    features: [
      "Platforms: Facebook & Instagram",
      "12 Designed Posts with Copywriting",
      "Contact Us Page (with Google Map Integration)",
      "Competitive Analysis",
      "Audit + Recommendation",
      "Content Calendar",
      "Industry & Keyword Research",
      "Social Media Copywriting",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "Money-Back Guarantee",
    ],
  },
  {
    name: "Pro Video Marketing",
    price: "$499",
    description: "Enhanced pro package with video/GIF creatives, ads setup, analytics, and deeper analysis—ideal for businesses wanting visual impact and early paid promotion.",
    popular: true,
    features: [
      "Platforms: Facebook & Instagram",
      "15 Designed Posts with Copywriting",
      "Social Media Marketing Strategy",
      "Competitive Analysis",
      "Brand Reputation Analysis",
      "Audit + Recommendation",
      "Monthly Reporting and Analytics",
      "1 GIF Creative",
      "Content Calendar",
      "Industry and Keyword Research",
      "Social Media Copywriting",
      "1 Ads Campaign Setup (Free)",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "Money-Back Guarantee",
    ],
  },
  {
    name: "SMM Elite",
    price: "$1,399",
    description: "Premium elite package with multi-channel setup, community management, advanced ads (including A/B testing & replication), and included ad spend management—suited for scaling brands.",
    features: [
      "3 Channel Setup",
      "Platforms: Facebook, Instagram, Twitter",
      "18 Post Designs with Copywriting",
      "Social Media Marketing Strategy",
      "Competitive Analysis",
      "Brand Reputation Analysis",
      "Audit + Recommendation",
      "Community Management",
      "Monthly Reporting and Analytics",
      "3 GIF Creatives",
      "Content Calendar",
      "Industry & Keyword Research",
      "Social Media Copywriting",
      "Business Manager Setup",
      "3 Ads Campaign Setup",
      "A/B Testing",
      "Winning Adset Replication",
      "Monthly Ad Spend Management Fee Included",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "Money-Back Guarantee",
    ],
  },
  {
    name: "Startup SMM",
    price: "$349",
    description: "Perfect entry-level package for businesses starting their social media presence.",
    features: [
      "Social Media strategy will be devised",
      "Competitor Analysis",
      "Copywriting",
      "Content Plan Creation",
      "Social Media Posts (06/month)",
      "Facebook Ad Campaigns will be set up",
      "Community Management",
      "Page Management (Facebook, Instagram, and Twitter)",
      "Page Optimization",
      "Tracking Setup",
      "Facebook Shop Creation",
      "Lead Form Creation",
      "1000 Likes on Facebook page",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
  {
    name: "Professional SMM",
    price: "$649",
    popular: true,
    description: "Best choice for growing businesses ready for stronger engagement and leads.",
    features: [
      "Social Media strategy will be devised",
      "Competitor Analysis",
      "Copywriting",
      "Content Plan Creation",
      "Social Media Posts (10/month)",
      "Facebook Ad Campaigns will be set up",
      "Community Management",
      "Page Management (Facebook, Instagram, and Twitter)",
      "Page Optimization",
      "Tracking Setup",
      "Facebook Shop Creation",
      "Lead Form Creation",
      "1000 Likes on Facebook page",
      "1000 Likes on Instagram",
      "Page Moderation",
      "Facebook Ad Campaign Optimization",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
  {
    name: "PROFESSIONAL Video Package",
    price: "$1,149.99",
    description: "Premium package with heavy video focus for maximum reach and conversions.",
    features: [
      "Social Media strategy will be devised",
      "Competitor Analysis",
      "Copywriting",
      "Content Plan Creation",
      "Social Media Posts (15/month)",
      "Facebook Ad Campaigns will be set up",
      "Community Management",
      "Page Management (Facebook, Instagram, and Twitter)",
      "Page Optimization",
      "Tracking Setup",
      "Facebook Shop Creation",
      "Lead Form Creation",
      "10,000 Likes on Facebook page",
      "2,000 Likes on Instagram",
      "Page Moderation",
      "Facebook Ad Campaign Optimization",
      "Facebook Ads A/B Testing",
      "Social Media Listening",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
],

  "App Development": [
    {
      name: "Basic Package",
      price: "$999",
      description: "Perfect for starting with a simple, single-platform app.",
      features: [
        "Development for a single platform (iOS or Android)",
        "Basic UI/UX design",
        "Up to 5 unique app screens",
        "Standard features implementation",
        "2-week development timeline",
        "1 round of revisions",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) or IPA (iOS)",
      ],
    },
    {
      name: "Standard Package",
      price: "$1,999",
      popular: true,
      description: "Best choice for most local businesses – both platforms.",
      features: [
        "Development for both iOS and Android platforms",
        "Enhanced UI/UX design",
        "Up to 10 unique app screens",
        "Advanced features implementation",
        "4-week development timeline",
        "2 rounds of revisions",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) and IPA (iOS)",
      ],
    },
    {
      name: "Premium Package",
      price: "$4,999",
      description: "High-end custom app with unlimited flexibility.",
      features: [
        "Development for both iOS and Android platforms",
        "Custom UI/UX design",
        "Unlimited app screens",
        "Advanced features implementation with API integration",
        "8-week development timeline",
        "Unlimited rounds of revisions",
        "Priority support",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) and IPA (iOS)",
      ],
    },
    {
      name: "Starter E-Commerce Package",
      price: "$2,999",
      description: "Great entry for small shops wanting to sell online.",
      features: [
        "Development for a single platform (iOS or Android)",
        "Basic UI/UX design optimized for e-commerce functionalities",
        "Integration with popular payment gateways (e.g., PayPal, Stripe)",
        "Limited product catalog (up to 100 products)",
        "Standard features implementation (e.g., product search, cart management)",
        "8-week development timeline",
        "2 rounds of revisions",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) or IPA (iOS)",
      ],
    },
    {
      name: "Business E-Commerce Package",
      price: "$7,999",
      description: "Ideal for growing stores with more products and features.",
      features: [
        "Development for both iOS and Android platforms",
        "Custom UI/UX design tailored to your brand and target audience",
        "Integration with advanced payment gateways and inventory management systems",
        "Expanded product catalog (up to 500 products)",
        "Enhanced features implementation (e.g., personalized recommendations, wishlist)",
        "12-week development timeline",
        "3 rounds of revisions",
        "Priority support",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) and IPA (iOS)",
      ],
    },
    {
      name: "Enterprise E-Commerce Package",
      price: "$15,999",
      description: "Full-featured app for serious online sellers.",
      features: [
        "Development for both iOS and Android platforms",
        "Premium UI/UX design with advanced interactive elements and animations",
        "Integration with custom payment solutions and ERP systems",
        "Unlimited product catalog",
        "Comprehensive features implementation (e.g., loyalty programs, multi-language support)",
        "16-week development timeline",
        "Unlimited rounds of revisions",
        "Dedicated project manager",
        "24/7 priority support",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) and IPA (iOS)",
      ],
    },
  ],

  "Custom Development": [
    {
      name: "Basic Package",
      price: "$999",
      description: "Perfect for starting with a simple, single-platform app.",
      features: [
        "Development for a single platform (iOS or Android)",
        "Basic UI/UX design",
        "Up to 5 unique app screens",
        "Standard features implementation",
        "2-week development timeline",
        "1 round of revisions",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) or IPA (iOS)",
      ],
    },
    {
      name: "Standard Package",
      price: "$1,999",
      popular: true,
      description: "Best choice for most local businesses – both platforms.",
      features: [
        "Development for both iOS and Android platforms",
        "Enhanced UI/UX design",
        "Up to 10 unique app screens",
        "Advanced features implementation",
        "4-week development timeline",
        "2 rounds of revisions",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) and IPA (iOS)",
      ],
    },
    {
      name: "Premium Package",
      price: "$4,999",
      description: "High-end custom app with unlimited flexibility.",
      features: [
        "Development for both iOS and Android platforms",
        "Custom UI/UX design",
        "Unlimited app screens",
        "Advanced features implementation with API integration",
        "8-week development timeline",
        "Unlimited rounds of revisions",
        "Priority support",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) and IPA (iOS)",
      ],
    },
    {
      name: "Starter E-Commerce Package",
      price: "$2,999",
      description: "Great entry for small shops wanting to sell online.",
      features: [
        "Development for a single platform (iOS or Android)",
        "Basic UI/UX design optimized for e-commerce functionalities",
        "Integration with popular payment gateways (e.g., PayPal, Stripe)",
        "Limited product catalog (up to 100 products)",
        "Standard features implementation (e.g., product search, cart management)",
        "8-week development timeline",
        "2 rounds of revisions",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) or IPA (iOS)",
      ],
    },
    {
      name: "Business E-Commerce Package",
      price: "$7,999",
      description: "Ideal for growing stores with more products and features.",
      features: [
        "Development for both iOS and Android platforms",
        "Custom UI/UX design tailored to your brand and target audience",
        "Integration with advanced payment gateways and inventory management systems",
        "Expanded product catalog (up to 500 products)",
        "Enhanced features implementation (e.g., personalized recommendations, wishlist)",
        "12-week development timeline",
        "3 rounds of revisions",
        "Priority support",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) and IPA (iOS)",
      ],
    },
    {
      name: "Enterprise E-Commerce Package",
      price: "$15,999",
      description: "Full-featured app for serious online sellers.",
      features: [
        "Development for both iOS and Android platforms",
        "Premium UI/UX design with advanced interactive elements and animations",
        "Integration with custom payment solutions and ERP systems",
        "Unlimited product catalog",
        "Comprehensive features implementation (e.g., loyalty programs, multi-language support)",
        "16-week development timeline",
        "Unlimited rounds of revisions",
        "Dedicated project manager",
        "24/7 priority support",
        "Ownership rights",
        "Satisfaction guarantee",
        "Free delivery of final app files",
        "Supported formats: APK (Android) and IPA (iOS)",
      ],
    },
  ],
"Branding": [
  {
    name: "Essential Brand Package",
    price: "$499",
    description: "Great starting point for new or very small businesses.",
    features: [
      "Custom logo (3 different concepts)",
      "Main logo + simplified version",
      "5-7 color palette",
      "Recommended fonts & sizes",
      "Short brand style guide (PDF)",
      "Social media icons & covers",
      "Business card layout (both sides)",
      "4 rounds of revisions",
      "All source + ready files",
      "100% ownership rights",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No monthly or hidden fees",
    ],
  },
  {
    name: "Professional Brand Package",
    price: "$799",
    popular: true,
    description: "Best choice for most local service businesses ready to stand out.",
    features: [
      "Everything in Essential Package",
      "Logo animation (simple loading version)",
      "Detailed brand style guide (10+ pages)",
      "5 ready social media post templates",
      "Professional email signature",
      "Letterhead & envelope design",
      "Favicon and small digital icons",
      "6 rounds of revisions",
      "Dedicated project manager",
      "Faster response times",
      "100% ownership rights",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No monthly or hidden fees",
    ],
  },
  {
    name: "Premium Brand Package",
    price: "$1,299",
    description: "High-end look for businesses that charge premium rates.",
    features: [
      "Everything in Professional Package",
      "Unlimited logo concepts & changes",
      "Short tagline + brand voice guide",
      "Mockups showing real-world use",
      "Vehicle magnet / van signage concept",
      "Basic packaging or label design",
      "Extra digital banners & covers",
      "Unlimited revisions during creation",
      "Final expert team review",
      "100% ownership rights",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No monthly or hidden fees",
    ],
  },
  {
    name: "Startup Collateral",
    price: "$99",
    description: "Ultra-affordable starter kit for essential print stationery—ideal for new businesses on a tight budget.",
    features: [
      "2-Set Stationery Design",
      "FREE Fax Template",
      "Print Ready Formats",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Collateral Classic",
    price: "$199",
    description: "Balanced collateral package adding professional flyers and brochures—great value for small businesses needing marketing materials.",
    popular: true,
    features: [
      "2-Set Stationery Design",
      "Unlimited Revisions",
      "Flyer Design",
      "Brochure Design (Bi-fold/Tri-fold)",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Premium Collateral",
    price: "$399",
    description: "Elevated package with packaging and apparel design—suitable for brands expanding visual identity beyond basics.",
    features: [
      "2-Set Stationery Design",
      "Packaging Design",
      "Unlimited Revisions",
      "T-Shirt Design",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    name: "Unlimited Collateral",
    price: "$499",
    description: "Comprehensive collateral bundle with menu, T-shirt, and banner—perfect for businesses wanting diverse print-ready assets.",
    features: [
      "2-Set Stationery Design",
      "Menu Card Design",
      "T-Shirt Design",
      "1 Banner Design",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
],
"Video Editing": [
  {
    name: "Starter Edits",
    price: "$349",
    description: "Great for small businesses and creators starting video content.",
    features: [
      "Up to 6 short videos per month",
      "Basic cuts, captions & transitions",
      "Simple color correction",
      "Stock music & sound effects",
      "1 round of revisions per video",
      "Delivery in 5–7 business days",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
  {
    name: "Professional Edits",
    price: "$649",
    popular: true,
    description: "Best choice for local businesses running ads and growing online.",
    features: [
      "Up to 12 short videos per month",
      "Advanced hooks & pacing",
      "Professional color grading",
      "Custom text animations & motion graphics",
      "Sound design & voiceover sync",
      "2 rounds of revisions per video",
      "Priority turnaround (3–5 days)",
      "Multiple aspect ratios & formats",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
  {
    name: "Premium Video Package",
    price: "$1,149",
    description: "High-end editing for brands wanting maximum impact and quality.",
    features: [
      "Up to 20 videos per month (short + long-form)",
      "Premium editing with cinematic feel",
      "Advanced motion graphics & VFX elements",
      "Custom music editing & sound design",
      "Unlimited revisions during active month",
      "Dedicated editor + weekly calls",
      "4K delivery & source files",
      "Same-week turnaround on priority",
      "Satisfaction guarantee",
      "Money back guarantee",
      "No hidden fees",
    ],
  },
  {
    name: "Startup",
    price: "$399",
    description: "Budget-friendly entry-level animated explainer to quickly showcase your idea or product.",
    features: [
      "30-Second Duration in HD 1080p",
      "Professional Script",
      "Storyboard Design",
      "Animations & VFX",
      "Music And Foley",
      "Voice Over Artists",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "Money Back Guarantee",
    ],
  },
  {
    name: "Classic",
    price: "$799",
    description: "Standard 60-second explainer with unlimited revisions for polished startup or small business videos.",
    popular: true,
    features: [
      "60-Second Duration",
      "Professional Script",
      "Storyboard Design",
      "Animations & VFX",
      "Music And Foley",
      "Voice Over Artists",
      "Unlimited Revisions",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "Money Back Guarantee",
    ],
  },
  {
    name: "Premium",
    price: "$1,495",
    description: "Extended 90-second high-impact animated explainer for stronger storytelling and engagement.",
    features: [
      "90-Second Duration",
      "Professional Script",
      "Storyboard Design",
      "Animations & VFX",
      "Music And Foley",
      "Voice Over Artists",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "Money Back Guarantee",
    ],
  },
  {
    name: "Deluxe",
    price: "$1,995",
    description: "Premium 120-second custom explainer for detailed explanations, ideal for products or services needing depth.",
    features: [
      "120-Second Duration",
      "Professional Script",
      "Storyboard Design",
      "Animations & VFX",
      "Music And Foley",
      "Voice Over Artists",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "Money Back Guarantee",
    ],
  },
],
};

/* =======================
   PRICING PAGE COMPONENT
======================= */

export default function PricingCategoriesPage() {
  const categories = Object.keys(PRICING_CATEGORIES);
  const [activeCategory, setActiveCategory] = useState(categories[0]);

  return (
    <section className="pt-40 bg-white dark:bg-slate-950 min-h-screen">
      <div className="container mx-auto px-4">

        {/* Header */}
        <div className="text-center max-w-2xl mx-auto mb-20">
          <span className="text-primary font-black uppercase tracking-[0.2em] text-xs mb-4 block">
            Pricing
          </span>
          <h1 className="text-4xl md:text-5xl font-black tracking-tighter text-slate-900 dark:text-white mb-6">
            Transparent Pricing
          </h1>
          <p className="text-slate-500 dark:text-slate-400 text-lg">
            Choose a package that fits your stage of growth. No hidden fees.
          </p>
        </div>

        {/* Category Tabs */}
        <div className="flex gap-5 mb-16 overflow-x-auto whitespace-nowrap flex-nowrap md:flex-wrap md:justify-center">
          {categories.map((category) => (
            <button
              key={category}
              onClick={() => setActiveCategory(category)}
              className={`flex items-center gap-2 px-6 py-3 rounded-full font-bold transition-all border
                ${activeCategory === category
                  ? "bg-primary text-white border-primary shadow-lg"
                  : "bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-400 border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700"
                }`}
            >
              <span className={activeCategory === category ? "text-white" : ""}>
                {CATEGORY_ICONS[category]}
              </span>
              {category}
            </button>
          ))}
        </div>

        {/* Pricing Cards */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
          {PRICING_CATEGORIES[activeCategory].map((plan, i) => (
            <div
              key={i}
              className={`relative p-8 rounded-[2.5rem] border transition-all h-full flex flex-col
                ${plan.popular
                  ? "bg-slate-900 dark:bg-slate-800 text-white shadow-2xl scale-105 z-10 border-slate-900"
                  : "bg-white dark:bg-slate-900 text-slate-900 dark:text-white border-slate-100 dark:border-slate-800 hover:shadow-xl"
                }`}
            >
              {/* Popular Badge */}
              {plan.popular && (
                <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-gradient-to-r from-primary to-blue-600 text-white text-[10px] font-black px-4 py-1.5 rounded-full uppercase tracking-widest">
                  Most Popular
                </div>
              )}

              {/* Plan Info */}
              <div className="mb-8">
                <h3 className="text-2xl font-black mb-2">{plan.name}</h3>
                <p className="text-sm opacity-70 mb-6 min-h-[40px]">
                  {plan.description}
                </p>
                <div className="text-4xl font-black tracking-tight">
                  {plan.price}
                </div>
              </div>

              {/* Features */}
              <div className="space-y-4 mb-10 flex-grow h-[20rem] overflow-y-auto pr-2">
                {plan.features.map((feature, j) => (
                  <div key={j} className="flex items-start gap-3 text-sm font-bold">
                    <CheckCircle2
                      size={18}
                      className={plan.popular ? "text-primary" : "text-green-500"}
                    />
                    <span
                      className={
                        plan.popular
                          ? "text-slate-200"
                          : "text-slate-600 dark:text-slate-400"
                      }
                    >
                      {feature}
                    </span>
                  </div>
                ))}
              </div>

              {/* CTA */}
              <button
                onClick={() => {
                  const element = document.getElementById("booking-form");
                  if (element) {
                    const yOffset = -80; // adjust this value based on your header height (e.g. -80px or -20rem)
                    const y = element.getBoundingClientRect().top + window.scrollY + yOffset;
                    window.scrollTo({ top: y, behavior: "smooth" });
                  }
                }}
                className={`w-full py-4 rounded-xl font-black transition
    ${plan.popular
                    ? "bg-white text-slate-900 hover:bg-slate-100"
                    : "bg-slate-900 dark:bg-white text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-200"
                  }`}
              >
                Choose {plan.name}
              </button>
            </div>
          ))}
        </div>
        
      </div>
      <BlurIn delay={0.2}>
          <div id="booking-form" className="scroll-mt-24 mt-12">
            {/* BookingSection uses its own full styling */}
            <BookingSection />
          </div>
        </BlurIn>
    </section>
    
  );
}